#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "20"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "30"

echo "# Installing Librewolf"
/usr/bin/flatpak install --user --noninteractive flathub io.gitlab.librewolf-community
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Librewolf Failed"
        exit 1
fi
echo "40"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "50"

echo "# Installing Nomacs"
/usr/bin/flatpak install --user --noninteractive flathub org.nomacs.ImageLounge
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Nomacs Failed"
        exit 1
fi
echo "60"

echo "# Installing GPU Screen Recorder"
/usr/bin/flatpak install --user --noninteractive flathub com.dec05eba.gpu_screen_recorder
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing GPU Screen Recorder Failed"
        exit 1
fi
echo "65"

echo "# Installing Obsidian"
/usr/bin/flatpak install --user --noninteractive md.obsidian.Obsidian
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Obsidian Failed"
        exit 1
fi
echo "70"

echo "# Installing Vorta for BorgBackup"
/usr/bin/flatpak install --user --noninteractive com.borgbase.Vorta
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Vorta for BorgBackup Failed"
        exit 1
fi
echo "80"

echo "# Installing MPV"
/usr/bin/flatpak install --user --noninteractive flathub io.mpv.Mpv
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing MPV Failed"
        exit 1
fi
echo "95"

echo "# Installing Antigen"
curl -L git.io/antigen > antigen.zsh
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Antigen Failed"
        exit 1
fi
echo "99"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done
cp -n /etc/justfile "$HOME"/.justfile

echo "100"

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot (reboot when done)" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi