default:
  @just --list

bios:
  systemctl reboot --firmware-setup

setup-refind:
  refind-install && refind-mkdefault
  sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/bobafetthotmail/refind-theme-regular/master/install.sh)"

changelogs:
  rpm-ostree db diff --changelogs
  
setup-flatpaks:
  echo 'Setting up your flatpaks...'
  flatpak install -y --user \\
  io.mpv.Mpv \\
  com.borgbase.Vorta \\
  md.obsidian.Obsidian \\
  com.dec05eba.gpu_screen_recorder \\
  com.github.tchx84.Flatseal \\
  io.gitlab.librewolf-community

setup-gaming:
  echo 'Setting up gaming experience ... lock and load.'
  flatpak install -y --user \\
  com.discordapp.Discord \\
  com.feaneron.Boatswain \\
  org.freedesktop.Platform.VulkanLayer.MangoHud//22.08 \\
  org.freedesktop.Platform.VulkanLayer.OBSVkCapture//22.08 \\
  org.freedesktop.Platform.VulkanLayer.vkBasalt//22.08 \\
  com.heroicgameslauncher.hgl \\
  com.obsproject.Studio \\
  com.obsproject.Studio.Plugin.OBSVkCapture \\
  com.obsproject.Studio.Plugin.Gstreamer \\
  com.usebottles.bottles \\
  com.valvesoftware.Steam \\
  com.valvesoftware.Steam.Utility.gamescope \\
  net.davidotek.pupgui2
  flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications 
  flatpak override --user --env=MANGOHUD=1 com.valvesoftware.Steam 
  flatpak override --user --env=MANGOHUD=1 com.heroicgameslauncher.hgl 
 
nvidia-kargs:
  rpm-ostree kargs \\
      --append=rd.driver.blacklist=nouveau \\
      --append=modprobe.blacklist=nouveau \\
      --append=nvidia-drm.modeset=1

update:
  rpm-ostree update
  flatpak update -y
  distrobox upgrade -a
